"""initial schema

Revision ID: 04f52a52a84a
Revises: 
Create Date: 2026-03-28 05:55:44.754468
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '04f52a52a84a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('org_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='orgrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'TEMPLATE', name='projectstatus'), nullable=False),
    sa.Column('total_length', sa.Float(), nullable=True),
    sa.Column('start_chainage', sa.Float(), nullable=False),
    sa.Column('end_chainage', sa.Float(), nullable=True),
    sa.Column('chainage_unit', sa.String(length=20), nullable=False),
    sa.Column('distance_direction', sa.String(length=20), nullable=False),
    sa.Column('data_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name='fk_project_calendar', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hours_per_day', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lbs_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_chainage', sa.Float(), nullable=False),
    sa.Column('end_chainage', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['lbs_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wbs_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['wbs_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=True),
    sa.Column('calendar_id', sa.UUID(), nullable=True),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('activity_type', sa.Enum('LINEAR', 'BLOCK', 'MILESTONE', 'CPM', 'LOE', 'SUMMARY', name='activitytype'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='activitystatus'), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('early_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('early_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('late_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('late_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('remaining_duration_hours', sa.Float(), nullable=True),
    sa.Column('total_float_hours', sa.Float(), nullable=True),
    sa.Column('free_float_hours', sa.Float(), nullable=True),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('start_chainage', sa.Float(), nullable=True),
    sa.Column('end_chainage', sa.Float(), nullable=True),
    sa.Column('direction', sa.Enum('INCREASING', 'DECREASING', name='workdirection'), nullable=True),
    sa.Column('production_rate', sa.Float(), nullable=True),
    sa.Column('production_rate_unit', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('line_width', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('source_format', sa.String(length=50), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('start_chainage', sa.Float(), nullable=False),
    sa.Column('end_chainage', sa.Float(), nullable=False),
    sa.Column('production_rate', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('predecessor_id', sa.UUID(), nullable=False),
    sa.Column('successor_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('FS', 'FF', 'SS', 'SF', name='dependencytype'), nullable=False),
    sa.Column('lag_hours', sa.Float(), nullable=False),
    sa.Column('lag_type', sa.Enum('TIME', 'DISTANCE', name='lagtype'), nullable=False),
    sa.Column('lag_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_dependency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependencies')
    op.drop_table('activity_segments')
    op.drop_table('calendar_exceptions')
    op.drop_table('activities')
    op.drop_table('wbs_nodes')
    op.drop_table('lbs_nodes')
    op.drop_table('calendars')
    op.drop_table('baselines')
    op.drop_table('projects')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
